export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS companies (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    sector TEXT,
    stage TEXT,
    geography TEXT,
    website TEXT,
    description TEXT,
    foundedDate TEXT,
    employeeCount INTEGER,
    fundingTotal REAL,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS funds (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    vintageYear INTEGER,
    targetSize REAL,
    strategy TEXT,
    createdAt TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS theses (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    fundId TEXT,
    sectors TEXT NOT NULL,
    stages TEXT NOT NULL,
    geographies TEXT NOT NULL,
    ownershipTargetMin REAL,
    ownershipTargetMax REAL,
    preferredFounderPatterns TEXT NOT NULL,
    antiPatterns TEXT NOT NULL,
    diligenceQuestions TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL,
    FOREIGN KEY (fundId) REFERENCES funds(id)
  )`,
  `CREATE TABLE IF NOT EXISTS deals (
    id TEXT PRIMARY KEY,
    companyId TEXT NOT NULL,
    fundId TEXT,
    stage TEXT NOT NULL,
    confidence INTEGER,
    leadPartner TEXT,
    source TEXT,
    thesisId TEXT,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL,
    lastActivityAt TEXT NOT NULL,
    FOREIGN KEY (companyId) REFERENCES companies(id),
    FOREIGN KEY (fundId) REFERENCES funds(id),
    FOREIGN KEY (thesisId) REFERENCES theses(id)
  )`,
  `CREATE TABLE IF NOT EXISTS people (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    role TEXT,
    companyId TEXT,
    linkedinUrl TEXT,
    relationshipScore INTEGER,
    lastContactAt TEXT,
    tags TEXT NOT NULL,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL,
    FOREIGN KEY (companyId) REFERENCES companies(id)
  )`,
  `CREATE TABLE IF NOT EXISTS meetings (
    id TEXT PRIMARY KEY,
    dealId TEXT,
    date TEXT NOT NULL,
    attendees TEXT NOT NULL,
    meetingType TEXT NOT NULL,
    rawNotes TEXT,
    structuredNotes TEXT NOT NULL,
    createdAt TEXT NOT NULL,
    FOREIGN KEY (dealId) REFERENCES deals(id)
  )`,
  `CREATE TABLE IF NOT EXISTS memos (
    id TEXT PRIMARY KEY,
    dealId TEXT,
    memoType TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT,
    status TEXT NOT NULL,
    author TEXT,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL,
    FOREIGN KEY (dealId) REFERENCES deals(id)
  )`,
  `CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    dealId TEXT,
    assignee TEXT,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL,
    dueDate TEXT,
    createdAt TEXT NOT NULL,
    completedAt TEXT,
    FOREIGN KEY (dealId) REFERENCES deals(id)
  )`,
  `CREATE INDEX IF NOT EXISTS deals_companyId_idx ON deals(companyId)`,
  `CREATE INDEX IF NOT EXISTS deals_stage_idx ON deals(stage)`,
  `CREATE INDEX IF NOT EXISTS deals_thesisId_idx ON deals(thesisId)`,
  `CREATE INDEX IF NOT EXISTS meetings_dealId_idx ON meetings(dealId)`,
  `CREATE INDEX IF NOT EXISTS memos_dealId_idx ON memos(dealId)`,
  `CREATE INDEX IF NOT EXISTS tasks_dealId_idx ON tasks(dealId)`,
  `CREATE INDEX IF NOT EXISTS people_companyId_idx ON people(companyId)`,
];
